name: unspash

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    volumes:
      - ./volumes/nginx:/build
    ports:
      - 8080:80
    env_file:
      - .env
    networks:
      - app_network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    volumes:
      - ./volumes/backend:/build
    ports:
      - 8888:8888
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    name: app_network
    driver: bridge